"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRightIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/forms/Field";
import { Input } from "@/components/ui/input";
import { compareRothTraditional } from "@/features/calculators/rothTraditional";

const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export function RothTraditionalCalculator() {
  const [values, setValues] = useState({ grossContribution: "6000", currentTaxRatePercent: "22", futureTaxRatePercent: "22" });
  const [result, setResult] = useState<ReturnType<typeof compareRothTraditional> | null>(null);
  const [error, setError] = useState<string | null>(null);
  function update(name: keyof typeof values, value: string) { setValues((current) => ({ ...current, [name]: value })); }
  function calculate() { try { setResult(compareRothTraditional({ grossContribution: Number(values.grossContribution), currentTaxRatePercent: Number(values.currentTaxRatePercent), futureTaxRatePercent: Number(values.futureTaxRatePercent) })); setError(null); } catch (calculationError) { setResult(null); setError(calculationError instanceof Error ? calculationError.message : "Check your inputs and try again."); } }
  const comparisonLabel = result?.difference === undefined ? "Your difference" : result.difference > 0 ? `Roth is ahead by ${currency.format(result.difference)}` : result.difference < 0 ? `Traditional is ahead by ${currency.format(Math.abs(result.difference))}` : "The outcomes are equal";
  return <div className="grid gap-design-md lg:grid-cols-[minmax(0,1fr)_minmax(18rem,.8fr)]"><section className="panel panel-body" aria-labelledby="roth-inputs-heading"><h2 id="roth-inputs-heading" className="section-title">Compare tax treatment</h2><p className="mt-design-xs text-sm leading-6 text-muted-foreground">Use the same pre-tax amount and two illustrative tax rates.</p><form onSubmit={(event) => { event.preventDefault(); calculate(); }}><div className="mt-design-md grid gap-design-sm sm:grid-cols-2"><Field label="Pre-tax amount considered" hint="The same amount for both scenarios"><Input required type="number" min="0" max="1000000000" step="100" value={values.grossContribution} onChange={(event) => update("grossContribution", event.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? "roth-error" : undefined} /></Field><Field label="Current tax rate" hint="Illustrative marginal rate"><Input required type="number" min="0" max="100" step="0.1" value={values.currentTaxRatePercent} onChange={(event) => update("currentTaxRatePercent", event.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? "roth-error" : undefined} /></Field><Field label="Future tax rate" hint="Illustrative marginal rate"><Input required type="number" min="0" max="100" step="0.1" value={values.futureTaxRatePercent} onChange={(event) => update("futureTaxRatePercent", event.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? "roth-error" : undefined} /></Field></div><Button type="submit" className="mt-design-md">Compare</Button>{error && <p id="roth-error" role="alert" className="mt-design-sm text-sm text-destructive">{error}</p>}</form></section><section className="panel panel-body" aria-live="polite" aria-labelledby="roth-result-heading"><p className="eyebrow">Simplified comparison</p><h2 id="roth-result-heading" className="mt-design-xs section-title">{comparisonLabel}</h2>{result ? <dl className="mt-design-md grid gap-design-sm text-sm"><div className="flex justify-between gap-4 border-b border-border pb-design-xs"><dt className="text-muted-foreground">Roth after tax</dt><dd className="font-medium">{currency.format(result.rothAfterTaxValue)}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Traditional after tax</dt><dd className="font-medium">{currency.format(result.traditionalAfterTaxValue)}</dd></div></dl> : <p className="mt-design-xs text-sm leading-6 text-muted-foreground">Enter the amount and two tax rates to compare the simplified outcomes.</p>}<div className="mt-design-md border-t border-border pt-design-sm"><p className="text-xs leading-5 text-muted-foreground">This excludes growth, deductions, contribution limits, and account-specific rules. A positive difference favors Roth in this illustration.</p><Link href="/learn/roth-ira" className="text-link mt-design-sm">Learn about Roth IRAs <ArrowRightIcon className="size-4" /></Link></div></section></div>;
}
